// <auto-generated />
using System;
using Airlines.Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airlines.Infrastructure.Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119080944_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Airlines.Domain.AirplaneFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AirplaneFamilies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "Airbus",
                            Name = "A320"
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Boeing",
                            Name = "B737"
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "Sukhoi",
                            Name = "SSJ"
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "Irkut",
                            Name = "MC-21"
                        },
                        new
                        {
                            Id = 5,
                            Manufacturer = "Embraer",
                            Name = "E190"
                        },
                        new
                        {
                            Id = 6,
                            Manufacturer = "Bombardier",
                            Name = "CRJ"
                        },
                        new
                        {
                            Id = 7,
                            Manufacturer = "Tupolev",
                            Name = "Tu-204"
                        },
                        new
                        {
                            Id = 8,
                            Manufacturer = "Ilyushin",
                            Name = "Il-96"
                        },
                        new
                        {
                            Id = 9,
                            Manufacturer = "Airbus",
                            Name = "A350"
                        },
                        new
                        {
                            Id = 10,
                            Manufacturer = "Boeing",
                            Name = "B777"
                        });
                });

            modelBuilder.Entity("Airlines.Domain.AirplaneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CargoCapacity")
                        .HasColumnType("float");

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("int");

                    b.Property<double>("RangeOfFlight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("AirplaneModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargoCapacity = 20.0,
                            FamilyId = 1,
                            ModelName = "A320-200",
                            PassengerCapacity = 180,
                            RangeOfFlight = 6100.0
                        },
                        new
                        {
                            Id = 2,
                            CargoCapacity = 18.0,
                            FamilyId = 2,
                            ModelName = "737-800",
                            PassengerCapacity = 189,
                            RangeOfFlight = 5436.0
                        },
                        new
                        {
                            Id = 3,
                            CargoCapacity = 12.0,
                            FamilyId = 3,
                            ModelName = "SSJ100",
                            PassengerCapacity = 108,
                            RangeOfFlight = 4500.0
                        },
                        new
                        {
                            Id = 4,
                            CargoCapacity = 22.0,
                            FamilyId = 4,
                            ModelName = "MC-21-300",
                            PassengerCapacity = 211,
                            RangeOfFlight = 6000.0
                        },
                        new
                        {
                            Id = 5,
                            CargoCapacity = 10.0,
                            FamilyId = 5,
                            ModelName = "E190",
                            PassengerCapacity = 100,
                            RangeOfFlight = 4400.0
                        },
                        new
                        {
                            Id = 6,
                            CargoCapacity = 8.0,
                            FamilyId = 6,
                            ModelName = "CRJ900",
                            PassengerCapacity = 90,
                            RangeOfFlight = 2800.0
                        },
                        new
                        {
                            Id = 7,
                            CargoCapacity = 25.0,
                            FamilyId = 7,
                            ModelName = "Tu-204-300",
                            PassengerCapacity = 230,
                            RangeOfFlight = 9000.0
                        },
                        new
                        {
                            Id = 8,
                            CargoCapacity = 40.0,
                            FamilyId = 8,
                            ModelName = "Il-96-300",
                            PassengerCapacity = 262,
                            RangeOfFlight = 11000.0
                        },
                        new
                        {
                            Id = 9,
                            CargoCapacity = 45.0,
                            FamilyId = 9,
                            ModelName = "A350-900",
                            PassengerCapacity = 350,
                            RangeOfFlight = 15000.0
                        },
                        new
                        {
                            Id = 10,
                            CargoCapacity = 50.0,
                            FamilyId = 10,
                            ModelName = "B777-300ER",
                            PassengerCapacity = 396,
                            RangeOfFlight = 13650.0
                        });
                });

            modelBuilder.Entity("Airlines.Domain.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirplaneModelId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<string>("DepartureAirportCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<string>("DestinationAirportCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirplaneModelId = 1,
                            ArrivalDate = new DateOnly(2025, 10, 1),
                            DepartureAirportCode = "SVO",
                            DepartureDate = new DateOnly(2025, 10, 1),
                            DepartureTime = new TimeOnly(8, 30, 0),
                            DestinationAirportCode = "LED",
                            Duration = new TimeSpan(0, 1, 12, 0, 0),
                            FlightNumber = "SU100"
                        },
                        new
                        {
                            Id = 2,
                            AirplaneModelId = 2,
                            ArrivalDate = new DateOnly(2025, 10, 2),
                            DepartureAirportCode = "SVO",
                            DepartureDate = new DateOnly(2025, 10, 2),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            DestinationAirportCode = "LED",
                            Duration = new TimeSpan(0, 1, 12, 0, 0),
                            FlightNumber = "SU101"
                        },
                        new
                        {
                            Id = 3,
                            AirplaneModelId = 10,
                            ArrivalDate = new DateOnly(2025, 11, 1),
                            DepartureAirportCode = "CDG",
                            DepartureDate = new DateOnly(2025, 11, 1),
                            DepartureTime = new TimeOnly(10, 15, 0),
                            DestinationAirportCode = "JFK",
                            Duration = new TimeSpan(0, 8, 0, 0, 0),
                            FlightNumber = "AF200"
                        },
                        new
                        {
                            Id = 4,
                            AirplaneModelId = 9,
                            ArrivalDate = new DateOnly(2025, 12, 1),
                            DepartureAirportCode = "FRA",
                            DepartureDate = new DateOnly(2025, 12, 1),
                            DepartureTime = new TimeOnly(14, 45, 0),
                            DestinationAirportCode = "DXB",
                            Duration = new TimeSpan(0, 6, 30, 0, 0),
                            FlightNumber = "LH300"
                        },
                        new
                        {
                            Id = 5,
                            AirplaneModelId = 8,
                            ArrivalDate = new DateOnly(2025, 12, 5),
                            DepartureAirportCode = "SVO",
                            DepartureDate = new DateOnly(2025, 12, 5),
                            DepartureTime = new TimeOnly(21, 0, 0),
                            DestinationAirportCode = "PEK",
                            Duration = new TimeSpan(0, 7, 30, 0, 0),
                            FlightNumber = "SU400"
                        },
                        new
                        {
                            Id = 6,
                            AirplaneModelId = 6,
                            ArrivalDate = new DateOnly(2025, 9, 20),
                            DepartureAirportCode = "LTN",
                            DepartureDate = new DateOnly(2025, 9, 20),
                            DepartureTime = new TimeOnly(7, 10, 0),
                            DestinationAirportCode = "AMS",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            FlightNumber = "U600"
                        },
                        new
                        {
                            Id = 7,
                            AirplaneModelId = 10,
                            ArrivalDate = new DateOnly(2025, 9, 25),
                            DepartureAirportCode = "LHR",
                            DepartureDate = new DateOnly(2025, 9, 25),
                            DepartureTime = new TimeOnly(16, 0, 0),
                            DestinationAirportCode = "JFK",
                            Duration = new TimeSpan(0, 8, 0, 0, 0),
                            FlightNumber = "BA700"
                        },
                        new
                        {
                            Id = 8,
                            AirplaneModelId = 9,
                            ArrivalDate = new DateOnly(2025, 11, 16),
                            DepartureAirportCode = "AMS",
                            DepartureDate = new DateOnly(2025, 11, 15),
                            DepartureTime = new TimeOnly(18, 30, 0),
                            DestinationAirportCode = "NRT",
                            Duration = new TimeSpan(0, 11, 0, 0, 0),
                            FlightNumber = "KL800"
                        },
                        new
                        {
                            Id = 9,
                            AirplaneModelId = 8,
                            ArrivalDate = new DateOnly(2025, 10, 10),
                            DepartureAirportCode = "SVO",
                            DepartureDate = new DateOnly(2025, 10, 10),
                            DepartureTime = new TimeOnly(13, 20, 0),
                            DestinationAirportCode = "JFK",
                            Duration = new TimeSpan(0, 9, 0, 0, 0),
                            FlightNumber = "SU900"
                        },
                        new
                        {
                            Id = 10,
                            AirplaneModelId = 5,
                            ArrivalDate = new DateOnly(2025, 12, 31),
                            DepartureAirportCode = "NRT",
                            DepartureDate = new DateOnly(2025, 12, 31),
                            DepartureTime = new TimeOnly(9, 0, 0),
                            DestinationAirportCode = "HND",
                            Duration = new TimeSpan(0, 1, 6, 0, 0),
                            FlightNumber = "JL1000"
                        });
                });

            modelBuilder.Entity("Airlines.Domain.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfPassport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(2004, 6, 28),
                            FullName = "Jessica Parker",
                            NumberOfPassport = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1985, 3, 15),
                            FullName = "Anna Ivanova",
                            NumberOfPassport = "2345678901"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1992, 11, 10),
                            FullName = "John Smith",
                            NumberOfPassport = "3456789012"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(1988, 7, 7),
                            FullName = "Maria Gonzalez",
                            NumberOfPassport = "4567890123"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1995, 2, 28),
                            FullName = "Chen Wei",
                            NumberOfPassport = "5678901234"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(1993, 9, 14),
                            FullName = "Fatima Al-Farsi",
                            NumberOfPassport = "6789012345"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(1980, 12, 1),
                            FullName = "James Brown",
                            NumberOfPassport = "7890123456"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(1999, 8, 19),
                            FullName = "Sophia Lee",
                            NumberOfPassport = "8901234567"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateOnly(1987, 4, 9),
                            FullName = "Ahmed Khan",
                            NumberOfPassport = "9012345678"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateOnly(1991, 6, 30),
                            FullName = "Emily Davis",
                            NumberOfPassport = "0123456789"
                        });
                });

            modelBuilder.Entity("Airlines.Domain.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("HandLuggageAvailability")
                        .HasColumnType("bit");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalBaggageWeight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 1,
                            HandLuggageAvailability = true,
                            PassengerId = 1,
                            SeatNumber = "12A",
                            TotalBaggageWeight = 0.0
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 1,
                            HandLuggageAvailability = false,
                            PassengerId = 2,
                            SeatNumber = "14C",
                            TotalBaggageWeight = 20.0
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 1,
                            HandLuggageAvailability = true,
                            PassengerId = 3,
                            SeatNumber = "22B",
                            TotalBaggageWeight = 0.0
                        },
                        new
                        {
                            Id = 4,
                            FlightId = 3,
                            HandLuggageAvailability = true,
                            PassengerId = 4,
                            SeatNumber = "1A",
                            TotalBaggageWeight = 8.0
                        },
                        new
                        {
                            Id = 5,
                            FlightId = 5,
                            HandLuggageAvailability = true,
                            PassengerId = 5,
                            SeatNumber = "5D",
                            TotalBaggageWeight = 25.0
                        },
                        new
                        {
                            Id = 6,
                            FlightId = 6,
                            HandLuggageAvailability = false,
                            PassengerId = 6,
                            SeatNumber = "18F",
                            TotalBaggageWeight = 30.0
                        },
                        new
                        {
                            Id = 7,
                            FlightId = 6,
                            HandLuggageAvailability = true,
                            PassengerId = 7,
                            SeatNumber = "8C",
                            TotalBaggageWeight = 12.0
                        },
                        new
                        {
                            Id = 8,
                            FlightId = 8,
                            HandLuggageAvailability = true,
                            PassengerId = 8,
                            SeatNumber = "9B",
                            TotalBaggageWeight = 18.0
                        },
                        new
                        {
                            Id = 9,
                            FlightId = 9,
                            HandLuggageAvailability = true,
                            PassengerId = 9,
                            SeatNumber = "2E",
                            TotalBaggageWeight = 28.0
                        },
                        new
                        {
                            Id = 10,
                            FlightId = 10,
                            HandLuggageAvailability = false,
                            PassengerId = 10,
                            SeatNumber = "3A",
                            TotalBaggageWeight = 22.0
                        });
                });

            modelBuilder.Entity("Airlines.Domain.AirplaneModel", b =>
                {
                    b.HasOne("Airlines.Domain.AirplaneFamily", "AirplaneFamily")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirplaneFamily");
                });
#pragma warning restore 612, 618
        }
    }
}
